shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false

default:
  index:
    security: true
    credentials:
      - [admin, empleado]
  insert:
    security: true
    credentials:
      - [admin, usuario]
  create:
    security: true 
    credentials:
      - [admin, usuario]
  edit:
    security: true 
    credentials:
      - [admin, usuario]
  update:
    security: true
    credentials:
      - [admin, usuario]
  delete:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelect:
    security: true
    credentials:
      - [admin, usuario]
  ver:
    security: true
    credentials:
      - [admin, usuario]
  reporte:
    security: true
    credentials:
      - [admin, usuario]
    
insumo:
  indexInsumo:
    security: true
    credentials:
      - [admin, usuario]
  insertInsumo:
    security: true
    credentials:
      - [admin, usuario]
  createInsumo:
    security: true 
    credentials:
      - [admin, usuario]
  editInsumo:
    security: true
    credentials:
      - [admin, usuario]
  updateInsumo:
    security: true
    credentials:
      - [admin, usuario]
  deleteInsumo:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelectInsumo:
    security: true
    credentials:
      - [admin, usuario]
  verInsumo:
    security: true
    credentials:
      - [admin, usuario]
  reportInsumo:
    security: true    
    credentials:
      - [admin]  
  indexTipoin:
    security: true
    credentials:
      - [admin, usuario]
  insertTipoin:
    security: true
    credentials:
      - [admin, usuario]
  createtipoin:
    security: true 
    credentials:
      - [admin, usuario]
  edittipoin:
    security: true
    credentials:
      - [admin, usuario]
  updatetipoin:
    security: true
    credentials:
      - [admin, usuario]
  deleteTipoin:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelectTipoin:
    security: true
    credentials:
      - [admin, usuario]
  verTipoin:
    security: true
    credentials:
      - [admin, usuario]
  reporttipoIn:
    security: true    
    credentials:
      - [admin]         
      
   
proveedor:
  indexProv:
    security: true
    credentials:
      - [admin, cajero]
  insertProv:
    security: true
    credentials:
      - [admin, usuario]
  createProv:
    security: true 
    credentials:
      - [admin, usuario]
  editProv:
    security: true 
    credentials:
      - [admin, usuario]
  updateProv:
    security: true
    credentials:
      - [admin, usuario]
  deleteProv:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelectProv:
    security: true
    credentials:
      - [admin, usuario]
  verProv:
    security: true
    credentials:
      - [admin, usuario]
  reporteProv:
    security: true
    credentials:
      - [admin, usuario]
  indexCiudad:
    security: true
    credentials:
      - [admin, cajero]
  insertCiudad:
    security: true
    credentials:
      - [admin, usuario]
  createCiudad:
    security: true 
    credentials:
      - [admin, usuario]
  editCiudad:
    security: true 
    credentials:
      - [admin, usuario]
  updateCiudad:
    security: true
    credentials:
      - [admin, usuario]
  deleteCiudad:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelectCiudad:
    security: true
    credentials:
      - [admin, usuario]
  verCiudad:
    security: true
    credentials:
      - [admin, usuario]
  reporteCiudad:
    security: true
    credentials:
      - [admin, usuario]

usuarioCredencial:
  indexUsuarioCredencial:
    security: true
    credentials:
      - [admin, empleado]
  insertUsuarioCredencial:
    security: true
    credentials:
      - [admin, usuario]
  createUsuarioCredencial:
    security: true 
    credentials:
      - [admin, usuario]
  editUsuarioCredencial:
    security: true 
    credentials:
      - [admin, usuario]
  update:
    security: true
    credentials:
      - [admin, usuario]
  deleteUsuarioCredencial:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelectUsuarioCredencial:
    security: true
    credentials:
      - [admin, usuario]
  verUsuarioCredencial:
    security: true
    credentials:
      - [admin, usuario]
  reporteUsuarioCredencial:
    security: true  
    credentials:
      - [admin, usuario]
    
credencial:
  index:
    security: true
    credentials:
      - [admin, empleado]
  insert:
    security: true
    credentials:
      - [admin, usuario]
  create:
    security: true 
    credentials:
      - [admin, usuario]
  edit:
    security: true 
    credentials:
      - [admin, usuario]
  update:
    security: true
    credentials:
      - [admin, usuario]
  delete:
    security: true
    credentials:
      - [admin, usuario]
  deleteSelect:
    security: true
    credentials:
      - [admin, usuario]
  ver:
    security: true
    credentials:
      - [admin, usuario]
  reporte:
    security: true
    credentials:
      - [admin, usuario]
 
empleado:
  index:
    security: true
    credentials:
      - [admin, empleado]
  insert:
    security: true
    credentials:
      - [admin, usuario]
  create:
    security: true 
    credentials:
      - [admin, usuario]
  edit:
    security: true 
    credentials:
      - [admin, usuario]
  update:
    security: true
    credentials:
      - [admin, usuario]
  delete:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelect:
    security: true
    credentials:
      - [admin, usuario]
  ver:
    security: true
    credentials:
      - [admin, usuario]
  reporte:
    security: true  
    credentials:
      - [admin, usuario]
    
paginaPrincipal:
  index:
    security: true
    credentials:
      - [admin, empleado]
      
sacrificioVenta:
  indexSacrificioVenta:
    security: true
    credentials:
      - [admin, usuario]
  insertSacrificioVenta:
    security: true
    credentials:
      - [admin, usuario]
  createSacrificioVenta:
    security: true 
    credentials:
      - [admin, usuario]
  editSacrificioVenta:
    security: true 
    credentials:
      - [admin, usuario]
  updateSacrificioVenta:
    security: true
    credentials:
      - [admin, usuario]
  deleteSacrificioVenta:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelectSacrificioVenta:
    security: true
    credentials:
      - [admin, usuario]
  verSacrificioVenta:
    security: true
    credentials:
      - [admin, usuario]
  reporteSacrificioVenta:
    security: true 
    credentials:
      - [admin, usuario]
  indexTipov:
    security: true
    credentials:
      - [admin, cajero]
  insertTipov:
    security: true
    credentials:
      - [admin, usuario]
  createTipov:
    security: true 
    credentials:
      - [admin, usuario]
  editTipov:
    security: true 
    credentials:
      - [admin, usuario]
  updateTipov:
    security: true
    credentials:
      - [admin, usuario]
  deleteTipov:
    security: true
    credentials:
      - [admin, usuario]
  deleteSelectTipov:
    security: true
    credentials:
      - [admin, usuario]
  verTipov:
    security: true
    credentials:
      - [admin, usuario]
  reportTipov:
    security: true  
    credentials:
      - [admin, usuario]
    
parto:
  index:
    security: true
    credentials:
      - [admin, empleado]
  insert:
    security: true
    credentials:
      - [admin, usuario]
  create:
    security: true 
    credentials:
      - [admin, usuario]
  edit:
    security: true 
    credentials:
      - [admin, usuario]
  update:
    security: true
    credentials:
      - [admin, usuario]
  delete:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelect:
    security: true
    credentials:
      - [admin, usuario]
  ver:
    security: true
    credentials:
      - [admin, usuario]
  reporte:
    security: true
    credentials:
      - [admin, usuario]
    
animal:
  index:
    security: true
    credentials:
      - [admin, empleado]
  insert:
    security: true
    credentials:
      - [admin, usuario]
  create:
    security: true 
    credentials:
      - [admin, usuario]
  edit:
    security: true 
    credentials:
      - [admin, usuario]
  update:
    security: true
    credentials:
      - [admin, usuario]
  delete:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelect:
    security: true
    credentials:
      - [admin, usuario]
  ver:
    security: true
    credentials:
      - [admin, usuario]
  reporte:
    security: true 
    credentials:
      - [admin, usuario]
    
lote:
  index:
    security: true
    credentials:
      - [admin, empleado]
  insert:
    security: true
    credentials:
      - [admin, usuario]
  create:
    security: true 
    credentials:
      - [admin, usuario]
  edit:
    security: true 
    credentials:
      - [admin, usuario]
  update:
    security: true
    credentials:
      - [admin, usuario]
  delete:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelect:
    security: true
    credentials:
      - [admin, usuario]
  ver:
    security: true
    credentials:
      - [admin, usuario]
  reporte:
    security: true 
    credentials:
      - [admin, usuario]
    
vacunacion:
  indexVacunacion:
    security: true
    credentials:
      - [admin, empleado]
  insertVacunacion:
    security: true
    credentials:
      - [admin, usuario]
  createVacunacion:
    security: true
    credentials:
      - [admin, usuario]
  editVacunacion:
    security: true 
    credentials:
      - [admin, usuario]
  updateVacunacion:
    security: true
    credentials:
      - [admin, usuario]
  deleteVacunacion:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelectVacunacion:
    security: true
    credentials:
      - [admin, usuario]
  verVacunacion:
    security: true
    credentials:
      - [admin, usuario]
  reporteVacunacion:
    security: true  
    credentials:
      - [admin, usuario]
    
salidaBodega:
  indexSalidaBodega:
    security: true
    credentials:
      - [admin, empleado]
  insertSalidaBodega:
    security: true
    credentials:
      - [admin, usuario]
  createSalidaBodega:
    security: true 
    credentials:
      - [admin, usuario]
  editSalidaBodega:
    security: true 
    credentials:
      - [admin, usuario]
  updateSalidaBodega:
    security: true
    credentials:
      - [admin, usuario]
  deleteSalidaBodega:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelectSalidaBodega:
    security: true
    credentials:
      - [admin, usuario]
  verSalidaBodega:
    security: true
    credentials:
      - [admin, usuario]
  reporteSalidaBodega:
    security: true 
    credentials:
      - [admin, usuario]
    
detalleSalida:
  indexDetalleSalida:
    security: true
    credentials:
      - [admin, empleado]
  insertDetalleSalida:
    security: true
    credentials:
      - [admin, usuario]
  createDetalleSalida:
    security: true 
    credentials:
      - [admin, usuario]
  editDetalleSalida:
    security: true 
  updateDetalleSalida:
    security: true
    credentials:
      - [admin, usuario]
  deleteDetalleSalida:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelectDetalleSalida:
    security: true
    credentials:
      - [admin, usuario]
  verDetalleSalida:
    security: true
    credentials:
      - [admin, usuario]
  reporteDetalleSalida:
    security: true
    credentials:
      - [admin, usuario]
    
entrada:
  indexEn:
    security: true
    credentials:
      - [admin, empleado]
  insertEn:
    security: true
    credentials:
      - [admin, usuario]
  createEn:
    security: true 
    credentials:
      - [admin, usuario]
  editEn:
    security: true
    credentials:
      - [admin, usuario]
  updateEn:
    security: true
    credentials:
      - [admin, usuario]
  deleteEn:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelectEn:
    security: true
    credentials:
      - [admin, usuario]
  verEn:
    security: true
    credentials:
      - [admin, usuario]
  reporteEn:
    security: true  
    credentials:
      - [admin, usuario]
    
detalle:
  index:
    security: true
    credentials:
      - [admin, empleado]
  insert:
    security: true
    credentials:
      - [admin, usuario]
  create:
    security: true 
    credentials:
      - [admin, usuario]
  edit:
    security: true 
    credentials:
      - [admin, usuario]
  update:
    security: true
    credentials:
      - [admin, usuario]
  delete:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelect:
    security: true
    credentials:
      - [admin, usuario]
  ver:
    security: true
    credentials:
      - [admin, usuario]
  reporte:
    security: true 
    credentials:
      - [admin, usuario]
    
control:
  index:
    security: true
    credentials:
      - [admin, empleado]
  insert:
    security: true
    credentials:
      - [admin, usuario]
  create:
    security: true 
    credentials:
      - [admin, usuario]
  edit:
    security: true 
    credentials:
      - [admin, usuario]
  update:
    security: true
    credentials:
      - [admin, usuario]
  delete:
    security: true 
    credentials:
      - [admin, usuario]
  deleteSelect:
    security: true
    credentials:
      - [admin, usuario]
  ver:
    security: true
    credentials:
      - [admin, usuario]
  reporte:
    security: true  
    credentials:
      - [admin, usuario]
      
         
        

  