shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false

default:
  index:
    security: true
    credentials:
      - [admin, usuario]
  insert:
    security: true
    credentials:
      - [admin, usuario]
  create:
    security: true 
  edit:
    security: true 
  update:
    security: true
  delete:
    security: true 
  deleteSelect:
    security: true
  ver:
    security: true
  reporte:
    security: true
    
insumo:
  indexInsumo:
    security: true
    credentials:
      - [admin, usuario]
  insertInsumo:
    security: true
    credentials:
      - [admin, usuario]
  createInsumo:
    security: true 
    credentials:
      - [admin, usuario]
  editInsumo:
    security: true
    credentials:
      - [admin, usuario]
  updateInsumo:
    security: true
    credentials:
      - [admin, usuario]
  deleteInsumo:
    security: true 
  deleteSelectInsumo:
    security: true
  verInsumo:
    security: true
  reportInsumo:
    security: true    
    credentials:
      - [admin]    
   
