shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false

default:
  index:
    security: true
    credentials:
      - [admin, empleado]
  insert:
    security: true
    credentials:
      - [admin, usuario]
  create:
    security: true 
  edit:
    security: true 
  update:
    security: true
  delete:
    security: true 
  deleteSelect:
    security: true
  ver:
    security: true
  reporte:
    security: true
    
insumo:
  indexInsumo:
    security: true
    credentials:
      - [admin, usuario]
  insertInsumo:
    security: true
    credentials:
      - [admin, usuario]
  createInsumo:
    security: true 
    credentials:
      - [admin, usuario]
  editInsumo:
    security: true
    credentials:
      - [admin, usuario]
  updateInsumo:
    security: true
    credentials:
      - [admin, usuario]
  deleteInsumo:
    security: true 
  deleteSelectInsumo:
    security: true
  verInsumo:
    security: true
  reportInsumo:
    security: true    
    credentials:
      - [admin]  
  indexTipoin:
    security: true
    credentials:
      - [admin, usuario]
  insertTipoin:
    security: true
    credentials:
      - [admin, usuario]
  createtipoin:
    security: true 
    credentials:
      - [admin, usuario]
  edittipoin:
    security: true
    credentials:
      - [admin, usuario]
  updatetipoin:
    security: true
    credentials:
      - [admin, usuario]
  deleteTipoin:
    security: true 
  deleteSelectTipoin:
    security: true
  verTipoin:
    security: true
  reporttipoIn:
    security: true    
    credentials:
      - [admin]         
      
   
proveedor:
  indexProv:
    security: true
    credentials:
      - [admin, cajero]
  insertProv:
    security: true
  createProv:
    security: true 
  editProv:
    security: true 
  updateProv:
    security: true
  deleteProv:
    security: true 
  deleteSelectProv:
    security: true
  verProv:
    security: true
  reporteProv:
    security: true
  indexCiudad:
    security: true
    credentials:
      - [admin, cajero]
  insertCiudad:
    security: true
  createCiudad:
    security: true 
  editCiudad:
    security: true 
  updateCiudad:
    security: true
  deleteCiudad:
    security: true 
  deleteSelectCiudad:
    security: true
  verCiudad:
    security: true
  reporteCiudad:
    security: true

usuarioCredencial:
  indexUsuarioCredencial:
    security: true
    credentials:
      - [admin, empleado]
  insertUsuarioCredencial:
    security: true
    credentials:
      - [admin, usuario]
  createUsuarioCredencial:
    security: true 
  editUsuarioCredencial:
    security: true 
  update:
    security: true
  deleteUsuarioCredencial:
    security: true 
  deleteSelectUsuarioCredencial:
    security: true
  verUsuarioCredencial:
    security: true
  reporteUsuarioCredencial:
    security: true      
    
credencial:
  index:
    security: true
    credentials:
      - [admin, empleado]
  insert:
    security: true
    credentials:
      - [admin, usuario]
  create:
    security: true 
  edit:
    security: true 
  update:
    security: true
  delete:
    security: true 
  deleteSelect:
    security: true
  ver:
    security: true
  reporte:
    security: true    
 
empleado:
  index:
    security: true
    credentials:
      - [admin, empleado]
  insert:
    security: true
    credentials:
      - [admin, usuario]
  create:
    security: true 
  edit:
    security: true 
  update:
    security: true
  delete:
    security: true 
  deleteSelect:
    security: true
  ver:
    security: true
  reporte:
    security: true    
        

  