all:
  favicon: hola.ico
  title: titulo de la pagina general
  meta:
    - charset="UTF-8"
    - http-equiv="X-UA-Compatible" content="IE=edge"
  javascript:
    - jquery-1.11.1.min.js
    - index.js
    - bootstrap.js
    - main.js
    
  stylesheet:
    - bootstrap.css
    - main.css
    - font-awesome.min.css

shfSecurity:
  index:
    title: Identificacion de usuario
    stylesheet:
      - signin.css

default:
  index:
    javascript:
      - index.js

depto:
  indexDepto:
    javascript:
      - index.js
      
ciudad:
  indexCiudad:
    javascript:
      - index.js

lote:
  index:
    javascript:
      - index.js

raza:
  index:
    javascript:
      - index.js
      
parto:
  index:
    javascript:
      - index.js
      
proveedor:
  indexProv:
    javascript:
      - index.js 
      
sacrificioVenta:
  indexSacrificioVenta:
    javascript:
      - index.js 
  grafica: 
    javascript:
      - jqPlot/jquery.jqplot.min.js 
      - jqPlot/plugins/jqplot.canvasTextRenderer.min.js
      - jqPlot/plugins/jqplot.canvasAxisLabelRenderer.min.js
      - graficas/grafica1.js
    stylesheet:
      - jquery.jqplot.min.css   
      
reporte:
  index:
    javascript:
      - index.js 
  grafica: 
    javascript:
      - jqPlot/jquery.jqplot.min.js
      # - jqPlot/plugins/jqplot.canvasTextRenderer.min.js
      # - jqPlot/plugins/jqplot.canvasAxisLabelRenderer.min.js
      - jqPlot/plugins/jqplot.categoryAxisRenderer.js
      # - jqPlot/plugins/jqplot.barRenderer.js
      # - jqPlot/plugins/jqplot.dateAxisRenderer.js 
      # - jqPlot/plugins/jqplot.logAxisRenderer.js
      - jqPlotplugins/jqplot.canvasAxisTickRenderer.js
      # - jqPlotp/js/jquery-ui.min.js
      - graficas/grafica1.js
#      - jqPlot/jquery-ui/js/jquery-ui.min.js
#      - jqPlot/jquery.jqplot.js
    stylesheet:
      - jquery.jqplot.min.css 
      - jqPlot/jquery.jqplot.css
      