--
-- PostgreSQL database dump
--

-- Dumped from database version 9.3.4
-- Dumped by pg_dump version 9.3.4
-- Started on 2015-04-29 09:00:12 COT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- TOC entry 226 (class 3079 OID 11829)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2408 (class 0 OID 0)
-- Dependencies: 226
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

--
-- TOC entry 170 (class 1259 OID 17893)
-- Name: bitacora_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE bitacora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.bitacora_id_seq OWNER TO postgres;

--
-- TOC entry 2409 (class 0 OID 0)
-- Dependencies: 170
-- Name: SEQUENCE bitacora_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 199 (class 1259 OID 17951)
-- Name: bitacora; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE bitacora (
    id bigint DEFAULT nextval('bitacora_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    accion character varying(80) NOT NULL,
    tabla character varying(80) NOT NULL,
    registro bigint,
    observacion character varying(1024),
    fecha timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.bitacora OWNER TO postgres;

--
-- TOC entry 171 (class 1259 OID 17895)
-- Name: ciudad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE ciudad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.ciudad_id_seq OWNER TO postgres;

--
-- TOC entry 2410 (class 0 OID 0)
-- Dependencies: 171
-- Name: SEQUENCE ciudad_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE ciudad_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 200 (class 1259 OID 17963)
-- Name: ciudad; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE ciudad (
    id bigint DEFAULT nextval('ciudad_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nom_ciudad character varying(90),
    depto_id bigint NOT NULL
);


ALTER TABLE public.ciudad OWNER TO postgres;

--
-- TOC entry 176 (class 1259 OID 17905)
-- Name: detalle_peso_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE detalle_peso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.detalle_peso_id_seq OWNER TO postgres;

--
-- TOC entry 2411 (class 0 OID 0)
-- Dependencies: 176
-- Name: SEQUENCE detalle_peso_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE detalle_peso_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 201 (class 1259 OID 17971)
-- Name: control_peso; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE control_peso (
    id bigint DEFAULT nextval('detalle_peso_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    peso_cerdo character varying(30),
    empleado_id bigint
);


ALTER TABLE public.control_peso OWNER TO postgres;

--
-- TOC entry 172 (class 1259 OID 17897)
-- Name: control_peso_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE control_peso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.control_peso_id_seq OWNER TO postgres;

--
-- TOC entry 2412 (class 0 OID 0)
-- Dependencies: 172
-- Name: SEQUENCE control_peso_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE control_peso_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 173 (class 1259 OID 17899)
-- Name: credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2413 (class 0 OID 0)
-- Dependencies: 173
-- Name: SEQUENCE credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 202 (class 1259 OID 17979)
-- Name: credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE credencial (
    id bigint DEFAULT nextval('credencial_id_seq'::regclass) NOT NULL,
    nombre character varying(80) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE public.credencial OWNER TO postgres;

--
-- TOC entry 2414 (class 0 OID 0)
-- Dependencies: 202
-- Name: TABLE credencial; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE credencial IS 'también conocido como CARGO';


--
-- TOC entry 174 (class 1259 OID 17901)
-- Name: depto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE depto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.depto_id_seq OWNER TO postgres;

--
-- TOC entry 2415 (class 0 OID 0)
-- Dependencies: 174
-- Name: SEQUENCE depto_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE depto_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 203 (class 1259 OID 17987)
-- Name: depto; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE depto (
    id bigint DEFAULT nextval('depto_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nom_depto character varying(90) NOT NULL
);


ALTER TABLE public.depto OWNER TO postgres;

--
-- TOC entry 175 (class 1259 OID 17903)
-- Name: detalle_entradaB_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_entradaB_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."detalle_entradaB_id_seq" OWNER TO postgres;

--
-- TOC entry 2416 (class 0 OID 0)
-- Dependencies: 175
-- Name: SEQUENCE "detalle_entradaB_id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_entradaB_id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 204 (class 1259 OID 17995)
-- Name: detalle_entradaB; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE "detalle_entradaB" (
    id bigint DEFAULT nextval('"detalle_entradaB_id_seq"'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    cantidad bigint NOT NULL,
    valor bigint NOT NULL,
    entrada_bodega_id bigint NOT NULL,
    insumo_id bigint
);


ALTER TABLE public."detalle_entradaB" OWNER TO postgres;

--
-- TOC entry 177 (class 1259 OID 17907)
-- Name: detalle_salidaB_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_salidaB_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."detalle_salidaB_id_seq" OWNER TO postgres;

--
-- TOC entry 2417 (class 0 OID 0)
-- Dependencies: 177
-- Name: SEQUENCE "detalle_salidaB_id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_salidaB_id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 205 (class 1259 OID 18003)
-- Name: detalle_salidaB; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE "detalle_salidaB" (
    id bigint DEFAULT nextval('"detalle_salidaB_id_seq"'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    cantidad bigint NOT NULL,
    valor bigint NOT NULL,
    salida_bodega_id bigint NOT NULL,
    insumo_id bigint
);


ALTER TABLE public."detalle_salidaB" OWNER TO postgres;

--
-- TOC entry 178 (class 1259 OID 17909)
-- Name: detalle_vacunacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE detalle_vacunacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.detalle_vacunacion_id_seq OWNER TO postgres;

--
-- TOC entry 2418 (class 0 OID 0)
-- Dependencies: 178
-- Name: SEQUENCE detalle_vacunacion_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE detalle_vacunacion_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 179 (class 1259 OID 17911)
-- Name: empleado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE empleado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.empleado_id_seq OWNER TO postgres;

--
-- TOC entry 2419 (class 0 OID 0)
-- Dependencies: 179
-- Name: SEQUENCE empleado_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE empleado_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 206 (class 1259 OID 18011)
-- Name: empleado; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE empleado (
    id bigint DEFAULT nextval('empleado_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(80) NOT NULL,
    usuario_id bigint NOT NULL,
    tipo_id_id bigint NOT NULL,
    apellido character varying(80),
    direccion character varying(100),
    correo character varying(50),
    telefono character varying(12)
);


ALTER TABLE public.empleado OWNER TO postgres;

--
-- TOC entry 180 (class 1259 OID 17913)
-- Name: entrada_bodega_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE entrada_bodega_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.entrada_bodega_id_seq OWNER TO postgres;

--
-- TOC entry 2420 (class 0 OID 0)
-- Dependencies: 180
-- Name: SEQUENCE entrada_bodega_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE entrada_bodega_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 207 (class 1259 OID 18021)
-- Name: entrada_bodega; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE entrada_bodega (
    id bigint DEFAULT nextval('entrada_bodega_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    empleado_id bigint,
    proveedor_id bigint
);


ALTER TABLE public.entrada_bodega OWNER TO postgres;

--
-- TOC entry 181 (class 1259 OID 17915)
-- Name: estado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE estado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.estado_id_seq OWNER TO postgres;

--
-- TOC entry 2421 (class 0 OID 0)
-- Dependencies: 181
-- Name: SEQUENCE estado_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE estado_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 208 (class 1259 OID 18029)
-- Name: estado; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE estado (
    id bigint DEFAULT nextval('estado_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    desc_estado character varying(80)
);


ALTER TABLE public.estado OWNER TO postgres;

--
-- TOC entry 182 (class 1259 OID 17917)
-- Name: hoja_vida_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE hoja_vida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hoja_vida_id_seq OWNER TO postgres;

--
-- TOC entry 2422 (class 0 OID 0)
-- Dependencies: 182
-- Name: SEQUENCE hoja_vida_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE hoja_vida_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 209 (class 1259 OID 18037)
-- Name: hoja_vida; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE hoja_vida (
    id bigint DEFAULT nextval('hoja_vida_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    genero character(1),
    fecha_nacimiento date,
    estado_id bigint,
    lote_id bigint,
    raza_id bigint,
    id_peso bigint,
    id_madre bigint
);


ALTER TABLE public.hoja_vida OWNER TO postgres;

--
-- TOC entry 183 (class 1259 OID 17919)
-- Name: insumo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE insumo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.insumo_id_seq OWNER TO postgres;

--
-- TOC entry 2423 (class 0 OID 0)
-- Dependencies: 183
-- Name: SEQUENCE insumo_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE insumo_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 210 (class 1259 OID 18045)
-- Name: insumo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE insumo (
    id bigint DEFAULT nextval('insumo_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    desc_insumo character varying(80),
    precio bigint NOT NULL,
    tipo_insumo_id bigint NOT NULL,
    fecha_fabricacion date NOT NULL,
    fecha_vencimiento date NOT NULL,
    proveedor_id bigint
);


ALTER TABLE public.insumo OWNER TO postgres;

--
-- TOC entry 184 (class 1259 OID 17921)
-- Name: inventario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE inventario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.inventario_id_seq OWNER TO postgres;

--
-- TOC entry 2424 (class 0 OID 0)
-- Dependencies: 184
-- Name: SEQUENCE inventario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE inventario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 211 (class 1259 OID 18053)
-- Name: inventario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE inventario (
    id bigint DEFAULT nextval('inventario_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    tipo_movimiento bigint,
    cantidad bigint NOT NULL,
    valor bigint NOT NULL,
    saldo bigint NOT NULL,
    insumo_id bigint NOT NULL,
    tipo_doc_id bigint NOT NULL
);


ALTER TABLE public.inventario OWNER TO postgres;

--
-- TOC entry 185 (class 1259 OID 17923)
-- Name: lote_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE lote_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.lote_id_seq OWNER TO postgres;

--
-- TOC entry 2425 (class 0 OID 0)
-- Dependencies: 185
-- Name: SEQUENCE lote_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE lote_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 212 (class 1259 OID 18061)
-- Name: lote; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE lote (
    id bigint DEFAULT nextval('lote_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    desc_lote character varying(80),
    ubicacion character varying(80)
);


ALTER TABLE public.lote OWNER TO postgres;

--
-- TOC entry 186 (class 1259 OID 17925)
-- Name: parto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE parto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.parto_id_seq OWNER TO postgres;

--
-- TOC entry 2426 (class 0 OID 0)
-- Dependencies: 186
-- Name: SEQUENCE parto_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE parto_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 213 (class 1259 OID 18069)
-- Name: parto; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE parto (
    id bigint DEFAULT nextval('parto_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    fecha_nacimiento character varying(10),
    num_nacidos integer,
    num_vivos integer,
    num_muertos integer,
    num_hembras integer,
    num_machos integer,
    fecha_montada time without time zone,
    id_padre integer,
    hoja_vida_id bigint
);


ALTER TABLE public.parto OWNER TO postgres;

--
-- TOC entry 187 (class 1259 OID 17927)
-- Name: proveedor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE proveedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.proveedor_id_seq OWNER TO postgres;

--
-- TOC entry 2427 (class 0 OID 0)
-- Dependencies: 187
-- Name: SEQUENCE proveedor_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE proveedor_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 214 (class 1259 OID 18077)
-- Name: proveedor; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE proveedor (
    id bigint DEFAULT nextval('proveedor_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(80),
    apellido character varying(80),
    direccion character varying(100),
    correo character varying(50),
    telefono character varying(12),
    ciudad_id bigint
);


ALTER TABLE public.proveedor OWNER TO postgres;

--
-- TOC entry 188 (class 1259 OID 17929)
-- Name: raza_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE raza_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.raza_id_seq OWNER TO postgres;

--
-- TOC entry 2428 (class 0 OID 0)
-- Dependencies: 188
-- Name: SEQUENCE raza_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE raza_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 215 (class 1259 OID 18085)
-- Name: raza; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE raza (
    id bigint DEFAULT nextval('raza_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    desc_raza character varying(80)
);


ALTER TABLE public.raza OWNER TO postgres;

--
-- TOC entry 189 (class 1259 OID 17931)
-- Name: recordar_me_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE recordar_me_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.recordar_me_id_seq OWNER TO postgres;

--
-- TOC entry 2429 (class 0 OID 0)
-- Dependencies: 189
-- Name: SEQUENCE recordar_me_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE recordar_me_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 216 (class 1259 OID 18093)
-- Name: recordar_me; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE recordar_me (
    id bigint DEFAULT nextval('recordar_me_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    ip_address character varying(50) NOT NULL,
    hash_cookie character varying(32) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.recordar_me OWNER TO postgres;

--
-- TOC entry 190 (class 1259 OID 17933)
-- Name: sacrificio_venta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE sacrificio_venta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sacrificio_venta_id_seq OWNER TO postgres;

--
-- TOC entry 2430 (class 0 OID 0)
-- Dependencies: 190
-- Name: SEQUENCE sacrificio_venta_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE sacrificio_venta_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 217 (class 1259 OID 18102)
-- Name: sacrificio_venta; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE sacrificio_venta (
    id bigint DEFAULT nextval('sacrificio_venta_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    valor bigint NOT NULL,
    tipo_venta_id bigint NOT NULL,
    id_cerdo bigint NOT NULL
);


ALTER TABLE public.sacrificio_venta OWNER TO postgres;

--
-- TOC entry 191 (class 1259 OID 17935)
-- Name: salida_bodega_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE salida_bodega_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.salida_bodega_id_seq OWNER TO postgres;

--
-- TOC entry 2431 (class 0 OID 0)
-- Dependencies: 191
-- Name: SEQUENCE salida_bodega_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE salida_bodega_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 218 (class 1259 OID 18110)
-- Name: salida_bodega; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE salida_bodega (
    id bigint DEFAULT nextval('salida_bodega_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    empleado_id bigint,
    tipo_doc_id bigint
);


ALTER TABLE public.salida_bodega OWNER TO postgres;

--
-- TOC entry 192 (class 1259 OID 17937)
-- Name: tipo_doc_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tipo_doc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tipo_doc_id_seq OWNER TO postgres;

--
-- TOC entry 2432 (class 0 OID 0)
-- Dependencies: 192
-- Name: SEQUENCE tipo_doc_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tipo_doc_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 219 (class 1259 OID 18118)
-- Name: tipo_doc; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_doc (
    id bigint DEFAULT nextval('tipo_doc_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    desc_tipo_doc character varying(20)
);


ALTER TABLE public.tipo_doc OWNER TO postgres;

--
-- TOC entry 193 (class 1259 OID 17939)
-- Name: tipo_id_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tipo_id_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tipo_id_id_seq OWNER TO postgres;

--
-- TOC entry 2433 (class 0 OID 0)
-- Dependencies: 193
-- Name: SEQUENCE tipo_id_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tipo_id_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 220 (class 1259 OID 18126)
-- Name: tipo_id; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_id (
    id bigint DEFAULT nextval('tipo_id_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    desc_tipo_id character varying(60)
);


ALTER TABLE public.tipo_id OWNER TO postgres;

--
-- TOC entry 194 (class 1259 OID 17941)
-- Name: tipo_insumo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tipo_insumo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tipo_insumo_id_seq OWNER TO postgres;

--
-- TOC entry 2434 (class 0 OID 0)
-- Dependencies: 194
-- Name: SEQUENCE tipo_insumo_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tipo_insumo_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 221 (class 1259 OID 18134)
-- Name: tipo_insumo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_insumo (
    id bigint DEFAULT nextval('tipo_insumo_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    desc_tipoin character varying(80)
);


ALTER TABLE public.tipo_insumo OWNER TO postgres;

--
-- TOC entry 195 (class 1259 OID 17943)
-- Name: tipo_venta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tipo_venta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tipo_venta_id_seq OWNER TO postgres;

--
-- TOC entry 2435 (class 0 OID 0)
-- Dependencies: 195
-- Name: SEQUENCE tipo_venta_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tipo_venta_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 222 (class 1259 OID 18142)
-- Name: tipo_venta; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_venta (
    id bigint DEFAULT nextval('tipo_venta_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    desc_tipov character varying(80)
);


ALTER TABLE public.tipo_venta OWNER TO postgres;

--
-- TOC entry 197 (class 1259 OID 17947)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuario_id_seq OWNER TO postgres;

--
-- TOC entry 2436 (class 0 OID 0)
-- Dependencies: 197
-- Name: SEQUENCE usuario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 223 (class 1259 OID 18150)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario (
    id bigint DEFAULT nextval('usuario_id_seq'::regclass) NOT NULL,
    user_name character varying(80) NOT NULL,
    password character varying(32) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    last_login_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 2437 (class 0 OID 0)
-- Dependencies: 223
-- Name: COLUMN usuario.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN usuario.actived IS 'TRUE = activado | FALSE = desactivado';


--
-- TOC entry 196 (class 1259 OID 17945)
-- Name: usuario_credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuario_credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2438 (class 0 OID 0)
-- Dependencies: 196
-- Name: SEQUENCE usuario_credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 224 (class 1259 OID 18163)
-- Name: usuario_credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario_credencial (
    id bigint DEFAULT nextval('usuario_credencial_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    credencial_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.usuario_credencial OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 18173)
-- Name: vacunacion; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE vacunacion (
    id bigint DEFAULT nextval('detalle_vacunacion_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    dosis character varying(6) NOT NULL,
    hora time without time zone NOT NULL,
    insumo_id bigint NOT NULL,
    id_cerdo bigint NOT NULL
);


ALTER TABLE public.vacunacion OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 17949)
-- Name: vacunacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE vacunacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.vacunacion_id_seq OWNER TO postgres;

--
-- TOC entry 2439 (class 0 OID 0)
-- Dependencies: 198
-- Name: SEQUENCE vacunacion_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE vacunacion_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 2375 (class 0 OID 17951)
-- Dependencies: 199
-- Data for Name: bitacora; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (1, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-13 18:36:36');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (2, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-13 18:37:16');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (3, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-13 18:45:19');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (4, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-13 19:35:48');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (5, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-13 21:05:06');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (6, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 07:46:16');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (7, 1, 'insertar', 'usuario', NULL, NULL, '2015-04-14 07:48:31');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (8, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 08:58:14');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (9, 1, 'editar', 'usuario', NULL, NULL, '2015-04-14 08:59:33');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (10, 1, 'insertar', 'usuario', NULL, NULL, '2015-04-14 09:00:08');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (11, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 09:09:39');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (12, 1, 'insertar', 'usuario', NULL, NULL, '2015-04-14 09:17:30');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (13, 1, 'insertar', 'usuario', NULL, NULL, '2015-04-14 09:17:51');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (14, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 13:11:36');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (15, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 13:37:57');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (16, 1, 'editar', 'usuario', NULL, NULL, '2015-04-14 13:38:09');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (17, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 14:00:17');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (18, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 14:30:22');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (19, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 14:50:38');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (20, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 14:57:04');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (21, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 15:01:57');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (22, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 15:28:15');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (23, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 15:31:05');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (24, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-14 15:53:36');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (25, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 15:53:41');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (26, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-14 15:53:57');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (27, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 15:54:36');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (28, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-14 16:15:12');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (29, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 16:34:02');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (30, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 18:20:18');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (31, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 18:33:38');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (32, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-14 19:03:49');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (33, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-15 08:22:54');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (34, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-15 09:07:51');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (35, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-15 09:08:40');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (36, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-16 10:30:17');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (37, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-16 10:41:44');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (38, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-16 11:39:22');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (39, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-16 11:39:28');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (40, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-16 14:00:14');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (41, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-16 14:37:40');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (42, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-16 14:42:10');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (43, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-16 14:42:15');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (44, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-16 14:42:20');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (45, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-16 14:47:28');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (46, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-16 14:59:40');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (47, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-16 16:04:12');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (48, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 10:12:47');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (49, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 12:40:06');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (50, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 14:11:40');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (51, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 15:19:06');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (52, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 16:25:28');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (53, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-17 16:27:01');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (54, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 16:27:22');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (55, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 17:37:21');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (56, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 18:00:04');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (57, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-17 18:00:13');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (58, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 18:00:19');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (59, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 18:21:08');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (60, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 19:03:07');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (61, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 19:10:08');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (62, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-18 09:21:43');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (63, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-18 09:23:18');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (64, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-18 09:23:23');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (65, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-18 09:23:51');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (66, 1, 'editar', 'usuario', NULL, NULL, '2015-04-18 09:24:42');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (67, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-18 11:59:55');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (68, 1, 'editar', 'usuario', NULL, NULL, '2015-04-18 12:19:33');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (69, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-18 12:19:52');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (70, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-18 12:22:36');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (71, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-18 12:24:54');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (72, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-18 12:46:07');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (73, 1, 'editar', 'usuario', NULL, NULL, '2015-04-18 12:50:52');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (74, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-18 14:53:36');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (75, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-18 17:40:37');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (76, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-18 17:40:58');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (77, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-18 17:47:30');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (78, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 11:46:16');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (79, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 14:57:00');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (80, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 15:07:46');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (81, 1, 'editar', 'usuario', NULL, NULL, '2015-04-19 15:07:48');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (82, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 15:14:55');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (83, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 16:09:41');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (84, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-19 16:09:43');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (85, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 17:57:38');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (86, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 18:27:20');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (87, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 18:45:12');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (88, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 18:48:31');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (89, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 18:52:06');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (90, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 18:56:29');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (91, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 18:58:26');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (92, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-19 19:03:50');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (93, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 19:03:59');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (94, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-19 19:21:51');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (95, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 19:24:44');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (96, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 20:49:57');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (97, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-19 21:07:32');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (98, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-20 08:51:25');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (99, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-20 09:24:37');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (100, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-20 09:43:35');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (101, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-20 10:04:48');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (102, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-20 10:11:36');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (103, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-20 15:21:56');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (104, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-20 18:23:00');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (105, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-21 08:00:38');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (106, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-21 08:48:16');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (107, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-21 08:49:30');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (108, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-21 10:20:25');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (109, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-21 14:02:05');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (110, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-23 08:49:34');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (111, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-23 09:10:58');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (112, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-23 09:22:56');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (113, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-23 09:23:03');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (114, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-23 11:17:48');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (115, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-23 16:12:20');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (116, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-23 16:17:08');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (117, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-23 16:25:58');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (118, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-23 16:31:17');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (119, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-23 16:32:23');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (120, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-23 16:32:47');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (121, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-23 17:22:16');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (122, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-28 13:28:39');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (123, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-28 13:38:38');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (124, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-28 17:11:34');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (125, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-28 17:12:23');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (126, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-28 17:36:16');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (127, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-28 19:35:31');


--
-- TOC entry 2440 (class 0 OID 0)
-- Dependencies: 170
-- Name: bitacora_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('bitacora_id_seq', 127, true);


--
-- TOC entry 2376 (class 0 OID 17963)
-- Dependencies: 200
-- Data for Name: ciudad; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO ciudad (id, created_at, updated_at, deleted_at, nom_ciudad, depto_id) VALUES (3, '2015-04-17 17:41:16.951533', '2015-04-17 17:41:16.951533', NULL, 'cali', 31);
INSERT INTO ciudad (id, created_at, updated_at, deleted_at, nom_ciudad, depto_id) VALUES (4, '2015-04-17 19:15:28.712439', '2015-04-17 19:15:28.712439', NULL, 'pradera', 31);


--
-- TOC entry 2441 (class 0 OID 0)
-- Dependencies: 171
-- Name: ciudad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('ciudad_id_seq', 4, true);


--
-- TOC entry 2377 (class 0 OID 17971)
-- Dependencies: 201
-- Data for Name: control_peso; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO control_peso (id, created_at, updated_at, deleted_at, peso_cerdo, empleado_id) VALUES (1, '2015-04-19 19:30:34.608247', '2015-04-19 19:30:34.608247', NULL, '30', 1);
INSERT INTO control_peso (id, created_at, updated_at, deleted_at, peso_cerdo, empleado_id) VALUES (2, '2015-04-19 19:33:17.371939', '2015-04-19 19:33:17.371939', NULL, '30', 1);
INSERT INTO control_peso (id, created_at, updated_at, deleted_at, peso_cerdo, empleado_id) VALUES (3, '2015-04-19 19:58:55.354176', '2015-04-19 19:58:55.354176', NULL, '34', 1);


--
-- TOC entry 2442 (class 0 OID 0)
-- Dependencies: 172
-- Name: control_peso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('control_peso_id_seq', 1, false);


--
-- TOC entry 2378 (class 0 OID 17979)
-- Dependencies: 202
-- Data for Name: credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO credencial (id, nombre, created_at, updated_at, deleted_at) VALUES (1, 'admin', '2015-04-13 18:35:58.083002', '2015-04-13 18:35:58.083002', NULL);


--
-- TOC entry 2443 (class 0 OID 0)
-- Dependencies: 173
-- Name: credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('credencial_id_seq', 2, true);


--
-- TOC entry 2379 (class 0 OID 17987)
-- Dependencies: 203
-- Data for Name: depto; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (5, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Boyaca');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (6, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Caldas');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (7, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Caqueta');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (8, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Casanare');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (9, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Cauca');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (10, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Cesar');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (11, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Choco');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (12, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Cordoba');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (13, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Cundinamarca');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (14, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Guainia');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (15, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Guaviare');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (17, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'La Guajira');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (18, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Magdalena');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (19, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Meta');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (21, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Norte de Santander');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (22, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Putumayo');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (23, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Quindio');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (24, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Risaralda');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (25, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'San Andres y Providencia');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (26, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Santander');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (27, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Sucre');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (28, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Tolima');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (29, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Amazonas');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (30, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Vaupes');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (32, '2015-04-17 00:00:00', '2015-04-17 00:00:00', '2015-04-17 00:00:00', 'Vichada');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (1, '2015-04-17 00:00:00', '2015-04-17 00:00:00', NULL, 'Antioquia');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (2, '2015-04-17 00:00:00', '2015-04-17 00:00:00', NULL, 'Arauca');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (3, '2015-04-17 00:00:00', '2015-04-17 00:00:00', NULL, 'Atlantico');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (4, '2015-04-17 00:00:00', '2015-04-17 00:00:00', NULL, 'Bolivar');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (31, '2015-04-17 00:00:00', '2015-04-17 00:00:00', NULL, 'Valle del Cauca');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (20, '2015-04-17 00:00:00', '2015-04-17 00:00:00', NULL, 'Narino');
INSERT INTO depto (id, created_at, updated_at, deleted_at, nom_depto) VALUES (16, '2015-04-17 00:00:00', '2015-04-17 00:00:00', NULL, 'Huila');


--
-- TOC entry 2444 (class 0 OID 0)
-- Dependencies: 174
-- Name: depto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('depto_id_seq', 2, true);


--
-- TOC entry 2380 (class 0 OID 17995)
-- Dependencies: 204
-- Data for Name: detalle_entradaB; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2445 (class 0 OID 0)
-- Dependencies: 175
-- Name: detalle_entradaB_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_entradaB_id_seq"', 1, false);


--
-- TOC entry 2446 (class 0 OID 0)
-- Dependencies: 176
-- Name: detalle_peso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('detalle_peso_id_seq', 3, true);


--
-- TOC entry 2381 (class 0 OID 18003)
-- Dependencies: 205
-- Data for Name: detalle_salidaB; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2447 (class 0 OID 0)
-- Dependencies: 177
-- Name: detalle_salidaB_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_salidaB_id_seq"', 1, false);


--
-- TOC entry 2448 (class 0 OID 0)
-- Dependencies: 178
-- Name: detalle_vacunacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('detalle_vacunacion_id_seq', 1, false);


--
-- TOC entry 2382 (class 0 OID 18011)
-- Dependencies: 206
-- Data for Name: empleado; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO empleado (id, created_at, updated_at, deleted_at, nombre, usuario_id, tipo_id_id, apellido, direccion, correo, telefono) VALUES (1, '2015-04-19 19:33:06.194643', '2015-04-19 19:33:06.194643', NULL, 'cristiano', 1, 1, 'castaño', 'car 12 #12', 'cristiano@gmail.com', '2673039');


--
-- TOC entry 2449 (class 0 OID 0)
-- Dependencies: 179
-- Name: empleado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('empleado_id_seq', 1, true);


--
-- TOC entry 2383 (class 0 OID 18021)
-- Dependencies: 207
-- Data for Name: entrada_bodega; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2450 (class 0 OID 0)
-- Dependencies: 180
-- Name: entrada_bodega_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('entrada_bodega_id_seq', 1, false);


--
-- TOC entry 2384 (class 0 OID 18029)
-- Dependencies: 208
-- Data for Name: estado; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2451 (class 0 OID 0)
-- Dependencies: 181
-- Name: estado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('estado_id_seq', 1, false);


--
-- TOC entry 2385 (class 0 OID 18037)
-- Dependencies: 209
-- Data for Name: hoja_vida; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2452 (class 0 OID 0)
-- Dependencies: 182
-- Name: hoja_vida_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('hoja_vida_id_seq', 1, false);


--
-- TOC entry 2386 (class 0 OID 18045)
-- Dependencies: 210
-- Data for Name: insumo; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO insumo (id, created_at, updated_at, deleted_at, desc_insumo, precio, tipo_insumo_id, fecha_fabricacion, fecha_vencimiento, proveedor_id) VALUES (7, '2015-04-17 17:44:38.850054', '2015-04-17 17:44:38.850054', NULL, 'trapeador', 2400, 9, '2001-02-08', '2015-04-01', 4);
INSERT INTO insumo (id, created_at, updated_at, deleted_at, desc_insumo, precio, tipo_insumo_id, fecha_fabricacion, fecha_vencimiento, proveedor_id) VALUES (9, '2015-04-28 13:39:23.72369', '2015-04-28 13:39:23.72369', NULL, 'millo', 1200, 10, '2015-04-28', '2015-04-14', 4);
INSERT INTO insumo (id, created_at, updated_at, deleted_at, desc_insumo, precio, tipo_insumo_id, fecha_fabricacion, fecha_vencimiento, proveedor_id) VALUES (10, '2015-04-28 13:41:23.998616', '2015-04-28 13:41:23.998616', '2015-04-28 13:41:30', 'aa', 1111111111111, 10, '2015-04-10', '2015-04-28', 3);
INSERT INTO insumo (id, created_at, updated_at, deleted_at, desc_insumo, precio, tipo_insumo_id, fecha_fabricacion, fecha_vencimiento, proveedor_id) VALUES (11, '2015-04-28 13:43:23.286484', '2015-04-28 13:43:23.286484', '2015-04-28 13:43:30', 'aa', 11, 10, '2015-04-16', '2015-04-23', 3);
INSERT INTO insumo (id, created_at, updated_at, deleted_at, desc_insumo, precio, tipo_insumo_id, fecha_fabricacion, fecha_vencimiento, proveedor_id) VALUES (8, '2015-04-20 09:58:37.256764', '2015-04-20 09:58:37.256764', NULL, 'arroz', 21, 10, '2015-12-17', '2015-12-17', 4);


--
-- TOC entry 2453 (class 0 OID 0)
-- Dependencies: 183
-- Name: insumo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('insumo_id_seq', 11, true);


--
-- TOC entry 2387 (class 0 OID 18053)
-- Dependencies: 211
-- Data for Name: inventario; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2454 (class 0 OID 0)
-- Dependencies: 184
-- Name: inventario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('inventario_id_seq', 1, false);


--
-- TOC entry 2388 (class 0 OID 18061)
-- Dependencies: 212
-- Data for Name: lote; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2455 (class 0 OID 0)
-- Dependencies: 185
-- Name: lote_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('lote_id_seq', 1, false);


--
-- TOC entry 2389 (class 0 OID 18069)
-- Dependencies: 213
-- Data for Name: parto; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2456 (class 0 OID 0)
-- Dependencies: 186
-- Name: parto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('parto_id_seq', 1, false);


--
-- TOC entry 2390 (class 0 OID 18077)
-- Dependencies: 214
-- Data for Name: proveedor; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO proveedor (id, created_at, updated_at, deleted_at, nombre, apellido, direccion, correo, telefono, ciudad_id) VALUES (3, '2015-04-17 17:42:12.351811', '2015-04-17 17:42:12.351811', NULL, 'andrea', 'castañeda', 'car 34 #43 ', 'andreas@hotmail.com', '234765', 3);
INSERT INTO proveedor (id, created_at, updated_at, deleted_at, nombre, apellido, direccion, correo, telefono, ciudad_id) VALUES (4, '2015-04-17 17:42:55.323012', '2015-04-17 17:42:55.323012', NULL, 'arbey', 'montaño', 'cal 12 carrera 20 #123', 'arbey@gmail.com', '3145212214', 3);
INSERT INTO proveedor (id, created_at, updated_at, deleted_at, nombre, apellido, direccion, correo, telefono, ciudad_id) VALUES (5, '2015-04-20 15:48:16.715233', '2015-04-20 15:48:16.715233', NULL, 'emanuel', 'armero', 'car 34 #43 ', 'andreas@hotmail.com', '2671343', 3);


--
-- TOC entry 2457 (class 0 OID 0)
-- Dependencies: 187
-- Name: proveedor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('proveedor_id_seq', 5, true);


--
-- TOC entry 2391 (class 0 OID 18085)
-- Dependencies: 215
-- Data for Name: raza; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO raza (id, created_at, updated_at, deleted_at, desc_raza) VALUES (1, '2015-04-13 00:00:00', '2015-04-13 00:00:00', '2015-04-13 00:00:00', 'Hampshire');
INSERT INTO raza (id, created_at, updated_at, deleted_at, desc_raza) VALUES (2, '2015-04-13 00:00:00', '2015-04-13 00:00:00', '2015-04-13 00:00:00', 'duroc');
INSERT INTO raza (id, created_at, updated_at, deleted_at, desc_raza) VALUES (3, '2015-04-13 00:00:00', '2015-04-13 00:00:00', '2015-04-13 00:00:00', 'Landrace');
INSERT INTO raza (id, created_at, updated_at, deleted_at, desc_raza) VALUES (4, '2015-04-13 00:00:00', '2015-04-13 00:00:00', '2015-04-13 00:00:00', 'SPOTTED POLAND');
INSERT INTO raza (id, created_at, updated_at, deleted_at, desc_raza) VALUES (5, '2015-04-13 00:00:00', '2015-04-13 00:00:00', '2015-04-13 00:00:00', 'Yorkshire');
INSERT INTO raza (id, created_at, updated_at, deleted_at, desc_raza) VALUES (6, '2015-04-13 00:00:00', '2015-04-13 00:00:00', '2015-04-13 00:00:00', 'Pietrain');


--
-- TOC entry 2458 (class 0 OID 0)
-- Dependencies: 188
-- Name: raza_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('raza_id_seq', 1, false);


--
-- TOC entry 2392 (class 0 OID 18093)
-- Dependencies: 216
-- Data for Name: recordar_me; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2459 (class 0 OID 0)
-- Dependencies: 189
-- Name: recordar_me_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('recordar_me_id_seq', 1, false);


--
-- TOC entry 2393 (class 0 OID 18102)
-- Dependencies: 217
-- Data for Name: sacrificio_venta; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2460 (class 0 OID 0)
-- Dependencies: 190
-- Name: sacrificio_venta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('sacrificio_venta_id_seq', 1, false);


--
-- TOC entry 2394 (class 0 OID 18110)
-- Dependencies: 218
-- Data for Name: salida_bodega; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2461 (class 0 OID 0)
-- Dependencies: 191
-- Name: salida_bodega_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('salida_bodega_id_seq', 1, false);


--
-- TOC entry 2395 (class 0 OID 18118)
-- Dependencies: 219
-- Data for Name: tipo_doc; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2462 (class 0 OID 0)
-- Dependencies: 192
-- Name: tipo_doc_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('tipo_doc_id_seq', 1, false);


--
-- TOC entry 2396 (class 0 OID 18126)
-- Dependencies: 220
-- Data for Name: tipo_id; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO tipo_id (id, created_at, updated_at, deleted_at, desc_tipo_id) VALUES (1, '2015-04-19 19:31:51.704805', '2015-04-19 19:31:51.704805', NULL, 'cedula');


--
-- TOC entry 2463 (class 0 OID 0)
-- Dependencies: 193
-- Name: tipo_id_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('tipo_id_id_seq', 1, true);


--
-- TOC entry 2397 (class 0 OID 18134)
-- Dependencies: 221
-- Data for Name: tipo_insumo; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO tipo_insumo (id, created_at, updated_at, deleted_at, desc_tipoin) VALUES (9, '2015-04-17 17:43:20.883837', '2015-04-17 17:43:20.883837', NULL, 'aseo');
INSERT INTO tipo_insumo (id, created_at, updated_at, deleted_at, desc_tipoin) VALUES (10, '2015-04-17 17:43:31.098379', '2015-04-17 17:43:31.098379', NULL, 'alimento');
INSERT INTO tipo_insumo (id, created_at, updated_at, deleted_at, desc_tipoin) VALUES (12, '2015-04-19 11:46:50.010334', '2015-04-19 11:46:50.010334', '2015-04-19 11:46:59', 'rrrrrrr');
INSERT INTO tipo_insumo (id, created_at, updated_at, deleted_at, desc_tipoin) VALUES (11, '2015-04-18 11:41:02.023168', '2015-04-18 11:41:02.023168', '2015-04-19 11:47:05', 'rrrrrrrrrrrrrrrrrrrrrr');


--
-- TOC entry 2464 (class 0 OID 0)
-- Dependencies: 194
-- Name: tipo_insumo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('tipo_insumo_id_seq', 12, true);


--
-- TOC entry 2398 (class 0 OID 18142)
-- Dependencies: 222
-- Data for Name: tipo_venta; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO tipo_venta (id, created_at, updated_at, deleted_at, desc_tipov) VALUES (1, '2015-04-13 18:43:24.622599', '2015-04-13 18:43:24.622599', NULL, 'costilla');


--
-- TOC entry 2465 (class 0 OID 0)
-- Dependencies: 195
-- Name: tipo_venta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('tipo_venta_id_seq', 1, true);


--
-- TOC entry 2399 (class 0 OID 18150)
-- Dependencies: 223
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (1, 'admin', '202cb962ac59075b964b07152d234b70', true, '2015-04-28 19:35:31', '2015-04-13 18:34:17.560088', '2015-04-13 18:34:17.560088', NULL);
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (6, 'consultor', '9b04d152845ec0a378394003c96da594', true, NULL, '2015-04-14 09:00:08.321466', '2015-04-14 09:00:08.321466', NULL);
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (7, 'leydy', 'dc513ea4fbdaa7a14786ffdebc4ef64e', true, NULL, '2015-04-14 09:17:29.916979', '2015-04-14 09:17:29.916979', NULL);
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (8, 'marcela', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-14 09:17:50.974505', '2015-04-14 09:17:50.974505', NULL);


--
-- TOC entry 2400 (class 0 OID 18163)
-- Dependencies: 224
-- Data for Name: usuario_credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO usuario_credencial (id, usuario_id, credencial_id, created_at) VALUES (1, 1, 1, '2015-04-13 18:36:19.95994');


--
-- TOC entry 2466 (class 0 OID 0)
-- Dependencies: 196
-- Name: usuario_credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_credencial_id_seq', 2, true);


--
-- TOC entry 2467 (class 0 OID 0)
-- Dependencies: 197
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_id_seq', 8, true);


--
-- TOC entry 2401 (class 0 OID 18173)
-- Dependencies: 225
-- Data for Name: vacunacion; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2468 (class 0 OID 0)
-- Dependencies: 198
-- Name: vacunacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('vacunacion_id_seq', 1, false);


--
-- TOC entry 2144 (class 2606 OID 17960)
-- Name: pkbitacora; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT pkbitacora PRIMARY KEY (id);


--
-- TOC entry 2146 (class 2606 OID 17970)
-- Name: pkciudad; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY ciudad
    ADD CONSTRAINT pkciudad PRIMARY KEY (id);


--
-- TOC entry 2148 (class 2606 OID 17978)
-- Name: pkcontrol_peso; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY control_peso
    ADD CONSTRAINT pkcontrol_peso PRIMARY KEY (id);


--
-- TOC entry 2150 (class 2606 OID 17986)
-- Name: pkcredencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY credencial
    ADD CONSTRAINT pkcredencial PRIMARY KEY (id);


--
-- TOC entry 2152 (class 2606 OID 17994)
-- Name: pkdepto; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY depto
    ADD CONSTRAINT pkdepto PRIMARY KEY (id);


--
-- TOC entry 2154 (class 2606 OID 18002)
-- Name: pkdetalle_entradaB; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY "detalle_entradaB"
    ADD CONSTRAINT "pkdetalle_entradaB" PRIMARY KEY (id);


--
-- TOC entry 2156 (class 2606 OID 18010)
-- Name: pkdetalle_salidaB; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY "detalle_salidaB"
    ADD CONSTRAINT "pkdetalle_salidaB" PRIMARY KEY (id);


--
-- TOC entry 2160 (class 2606 OID 18018)
-- Name: pkempleado; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT pkempleado PRIMARY KEY (id);


--
-- TOC entry 2162 (class 2606 OID 18028)
-- Name: pkentrada_bodega; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY entrada_bodega
    ADD CONSTRAINT pkentrada_bodega PRIMARY KEY (id);


--
-- TOC entry 2164 (class 2606 OID 18036)
-- Name: pkestado; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY estado
    ADD CONSTRAINT pkestado PRIMARY KEY (id);


--
-- TOC entry 2166 (class 2606 OID 18044)
-- Name: pkhoja_vida; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY hoja_vida
    ADD CONSTRAINT pkhoja_vida PRIMARY KEY (id);


--
-- TOC entry 2168 (class 2606 OID 18052)
-- Name: pkinsumo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY insumo
    ADD CONSTRAINT pkinsumo PRIMARY KEY (id);


--
-- TOC entry 2170 (class 2606 OID 18060)
-- Name: pkinventario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT pkinventario PRIMARY KEY (id);


--
-- TOC entry 2172 (class 2606 OID 18068)
-- Name: pklote; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY lote
    ADD CONSTRAINT pklote PRIMARY KEY (id);


--
-- TOC entry 2174 (class 2606 OID 18076)
-- Name: pkparto; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY parto
    ADD CONSTRAINT pkparto PRIMARY KEY (id);


--
-- TOC entry 2176 (class 2606 OID 18084)
-- Name: pkproveedor; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY proveedor
    ADD CONSTRAINT pkproveedor PRIMARY KEY (id);


--
-- TOC entry 2178 (class 2606 OID 18092)
-- Name: pkraza; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY raza
    ADD CONSTRAINT pkraza PRIMARY KEY (id);


--
-- TOC entry 2180 (class 2606 OID 18099)
-- Name: pkrecordar_me; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT pkrecordar_me PRIMARY KEY (id);


--
-- TOC entry 2184 (class 2606 OID 18109)
-- Name: pksacrificio_venta; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY sacrificio_venta
    ADD CONSTRAINT pksacrificio_venta PRIMARY KEY (id);


--
-- TOC entry 2186 (class 2606 OID 18117)
-- Name: pksalida_bodega; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY salida_bodega
    ADD CONSTRAINT pksalida_bodega PRIMARY KEY (id);


--
-- TOC entry 2188 (class 2606 OID 18125)
-- Name: pktipo_doc; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_doc
    ADD CONSTRAINT pktipo_doc PRIMARY KEY (id);


--
-- TOC entry 2190 (class 2606 OID 18133)
-- Name: pktipo_id; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_id
    ADD CONSTRAINT pktipo_id PRIMARY KEY (id);


--
-- TOC entry 2192 (class 2606 OID 18141)
-- Name: pktipo_insumo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_insumo
    ADD CONSTRAINT pktipo_insumo PRIMARY KEY (id);


--
-- TOC entry 2194 (class 2606 OID 18149)
-- Name: pktipo_venta; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_venta
    ADD CONSTRAINT pktipo_venta PRIMARY KEY (id);


--
-- TOC entry 2196 (class 2606 OID 18158)
-- Name: pkusuario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario
    ADD CONSTRAINT pkusuario PRIMARY KEY (id);


--
-- TOC entry 2202 (class 2606 OID 18169)
-- Name: pkusuario_credencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT pkusuario_credencial PRIMARY KEY (id);


--
-- TOC entry 2207 (class 2606 OID 18180)
-- Name: pkvacunacion; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY vacunacion
    ADD CONSTRAINT pkvacunacion PRIMARY KEY (id);


--
-- TOC entry 2141 (class 1259 OID 17961)
-- Name: bitacora_fecha_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_fecha_Idx" ON bitacora USING btree (fecha);


--
-- TOC entry 2142 (class 1259 OID 17962)
-- Name: bitacora_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_usuario_id_Idx" ON bitacora USING btree (usuario_id);


--
-- TOC entry 2157 (class 1259 OID 18019)
-- Name: empleado_tipo_id_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "empleado_tipo_id_id_Idx" ON empleado USING btree (tipo_id_id);


--
-- TOC entry 2158 (class 1259 OID 18020)
-- Name: empleado_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "empleado_usuario_id_Idx" ON empleado USING btree (usuario_id);


--
-- TOC entry 2181 (class 1259 OID 18100)
-- Name: recordar_me_ip_address_hash_cookie_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "recordar_me_ip_address_hash_cookie_Idx" ON recordar_me USING btree (ip_address, hash_cookie);


--
-- TOC entry 2182 (class 1259 OID 18101)
-- Name: recordar_me_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "recordar_me_usuario_id_Idx" ON recordar_me USING btree (usuario_id);


--
-- TOC entry 2197 (class 1259 OID 18159)
-- Name: usuario_actived_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_actived_Idx" ON usuario USING btree (actived);


--
-- TOC entry 2203 (class 1259 OID 18170)
-- Name: usuario_credencial_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_credencial_id_Idx" ON usuario_credencial USING btree (credencial_id);


--
-- TOC entry 2204 (class 1259 OID 18171)
-- Name: usuario_credencial_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_usuario_id_Idx" ON usuario_credencial USING btree (usuario_id);


--
-- TOC entry 2205 (class 1259 OID 18172)
-- Name: usuario_credencial_usuario_id_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial USING btree (usuario_id, credencial_id);


--
-- TOC entry 2198 (class 1259 OID 18160)
-- Name: usuario_deleted_at_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_deleted_at_Idx" ON usuario USING btree (deleted_at);


--
-- TOC entry 2199 (class 1259 OID 18161)
-- Name: usuario_user_name_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_user_name_Idx" ON usuario USING btree (user_name);


--
-- TOC entry 2200 (class 1259 OID 18162)
-- Name: usuario_user_name_password_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_user_name_password_Idx" ON usuario USING btree (user_name, password);


--
-- TOC entry 2208 (class 2606 OID 18181)
-- Name: fk_bitacora_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT fk_bitacora_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2209 (class 2606 OID 18186)
-- Name: fk_ciudad_depto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY ciudad
    ADD CONSTRAINT fk_ciudad_depto FOREIGN KEY (depto_id) REFERENCES depto(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2211 (class 2606 OID 18196)
-- Name: fk_detalle_entradaB_entrada_bodega; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "detalle_entradaB"
    ADD CONSTRAINT "fk_detalle_entradaB_entrada_bodega" FOREIGN KEY (entrada_bodega_id) REFERENCES entrada_bodega(id);


--
-- TOC entry 2212 (class 2606 OID 18201)
-- Name: fk_detalle_entradaB_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "detalle_entradaB"
    ADD CONSTRAINT "fk_detalle_entradaB_insumo" FOREIGN KEY (insumo_id) REFERENCES insumo(id);


--
-- TOC entry 2210 (class 2606 OID 18191)
-- Name: fk_detalle_peso_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY control_peso
    ADD CONSTRAINT fk_detalle_peso_empleado FOREIGN KEY (empleado_id) REFERENCES empleado(id);


--
-- TOC entry 2213 (class 2606 OID 18206)
-- Name: fk_detalle_salidaB_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "detalle_salidaB"
    ADD CONSTRAINT "fk_detalle_salidaB_insumo" FOREIGN KEY (insumo_id) REFERENCES insumo(id);


--
-- TOC entry 2214 (class 2606 OID 18211)
-- Name: fk_detalle_salidaB_salida_bodega; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "detalle_salidaB"
    ADD CONSTRAINT "fk_detalle_salidaB_salida_bodega" FOREIGN KEY (salida_bodega_id) REFERENCES salida_bodega(id);


--
-- TOC entry 2237 (class 2606 OID 18326)
-- Name: fk_detalle_vacunacion_hoja_vida; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY vacunacion
    ADD CONSTRAINT fk_detalle_vacunacion_hoja_vida FOREIGN KEY (id_cerdo) REFERENCES hoja_vida(id);


--
-- TOC entry 2238 (class 2606 OID 18331)
-- Name: fk_detalle_vacunacion_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY vacunacion
    ADD CONSTRAINT fk_detalle_vacunacion_insumo FOREIGN KEY (insumo_id) REFERENCES insumo(id);


--
-- TOC entry 2215 (class 2606 OID 18216)
-- Name: fk_empleado_tipo_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT fk_empleado_tipo_id FOREIGN KEY (tipo_id_id) REFERENCES tipo_id(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2216 (class 2606 OID 18221)
-- Name: fk_empleado_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT fk_empleado_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2217 (class 2606 OID 18226)
-- Name: fk_entrada_bodega_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY entrada_bodega
    ADD CONSTRAINT fk_entrada_bodega_empleado FOREIGN KEY (empleado_id) REFERENCES empleado(id);


--
-- TOC entry 2218 (class 2606 OID 18231)
-- Name: fk_entrada_bodega_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY entrada_bodega
    ADD CONSTRAINT fk_entrada_bodega_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedor(id);


--
-- TOC entry 2219 (class 2606 OID 18236)
-- Name: fk_hoja_vida_detalle_peso; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY hoja_vida
    ADD CONSTRAINT fk_hoja_vida_detalle_peso FOREIGN KEY (id_peso) REFERENCES control_peso(id);


--
-- TOC entry 2220 (class 2606 OID 18241)
-- Name: fk_hoja_vida_estado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY hoja_vida
    ADD CONSTRAINT fk_hoja_vida_estado FOREIGN KEY (estado_id) REFERENCES estado(id);


--
-- TOC entry 2221 (class 2606 OID 18246)
-- Name: fk_hoja_vida_hoja_vida; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY hoja_vida
    ADD CONSTRAINT fk_hoja_vida_hoja_vida FOREIGN KEY (id_madre) REFERENCES hoja_vida(id);


--
-- TOC entry 2222 (class 2606 OID 18251)
-- Name: fk_hoja_vida_lote; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY hoja_vida
    ADD CONSTRAINT fk_hoja_vida_lote FOREIGN KEY (lote_id) REFERENCES lote(id);


--
-- TOC entry 2223 (class 2606 OID 18256)
-- Name: fk_hoja_vida_raza; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY hoja_vida
    ADD CONSTRAINT fk_hoja_vida_raza FOREIGN KEY (raza_id) REFERENCES raza(id);


--
-- TOC entry 2224 (class 2606 OID 18261)
-- Name: fk_insumo_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY insumo
    ADD CONSTRAINT fk_insumo_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedor(id);


--
-- TOC entry 2225 (class 2606 OID 18266)
-- Name: fk_insumo_tipo_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY insumo
    ADD CONSTRAINT fk_insumo_tipo_insumo FOREIGN KEY (tipo_insumo_id) REFERENCES tipo_insumo(id);


--
-- TOC entry 2226 (class 2606 OID 18271)
-- Name: fk_inventario_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT fk_inventario_insumo FOREIGN KEY (insumo_id) REFERENCES insumo(id);


--
-- TOC entry 2227 (class 2606 OID 18276)
-- Name: fk_inventario_tipo_doc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT fk_inventario_tipo_doc FOREIGN KEY (tipo_doc_id) REFERENCES tipo_doc(id);


--
-- TOC entry 2228 (class 2606 OID 18281)
-- Name: fk_parto_hoja_vida; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY parto
    ADD CONSTRAINT fk_parto_hoja_vida FOREIGN KEY (hoja_vida_id) REFERENCES hoja_vida(id);


--
-- TOC entry 2229 (class 2606 OID 18286)
-- Name: fk_proveedor_ciudad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY proveedor
    ADD CONSTRAINT fk_proveedor_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudad(id);


--
-- TOC entry 2230 (class 2606 OID 18291)
-- Name: fk_recordar_me_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT fk_recordar_me_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2231 (class 2606 OID 18296)
-- Name: fk_sacrificio_venta_hoja_vida; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY sacrificio_venta
    ADD CONSTRAINT fk_sacrificio_venta_hoja_vida FOREIGN KEY (id_cerdo) REFERENCES hoja_vida(id);


--
-- TOC entry 2232 (class 2606 OID 18301)
-- Name: fk_sacrificio_venta_tipo_venta; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY sacrificio_venta
    ADD CONSTRAINT fk_sacrificio_venta_tipo_venta FOREIGN KEY (tipo_venta_id) REFERENCES tipo_venta(id);


--
-- TOC entry 2233 (class 2606 OID 18306)
-- Name: fk_salida_bodega_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY salida_bodega
    ADD CONSTRAINT fk_salida_bodega_empleado FOREIGN KEY (empleado_id) REFERENCES empleado(id);


--
-- TOC entry 2234 (class 2606 OID 18311)
-- Name: fk_salida_bodega_tipo_doc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY salida_bodega
    ADD CONSTRAINT fk_salida_bodega_tipo_doc FOREIGN KEY (tipo_doc_id) REFERENCES tipo_doc(id);


--
-- TOC entry 2235 (class 2606 OID 18316)
-- Name: fk_usuario_credencial_credencial; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_credencial FOREIGN KEY (credencial_id) REFERENCES credencial(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2236 (class 2606 OID 18321)
-- Name: fk_usuario_credencial_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2407 (class 0 OID 0)
-- Dependencies: 5
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2015-04-29 09:00:13 COT

--
-- PostgreSQL database dump complete
--

